CREATE TABLE IF NOT EXISTS user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email  VARCHAR(100) NOT NULL,
    userRoleID  INTEGER NOT NULL,

    FOREIGN KEY (userRoleID) REFERENCES  userRole(userRoleID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);