CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    userRoleID INT NOT NULL,

    FOREIGN KEY (userRoleID) REFERENCES userRole(userRoleID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)